#!/bin/bash
set -e

# Set the machine type, default is "fx1000"
MACHINE=${1:-"fx1000"}

# Initialize the Modules system
. /usr/share/Modules/init/bash

# Clear and reload the required modules
module purge

# Load the GFS modules
module use modulefiles
module load modulefile.tcogfs.${MACHINE}
module unuse modulefiles

# Set the build directory
BLD_DIR=build_${MACHINE}
[[ -e ${BLD_DIR} ]] && rm -rf ${BLD_DIR}

# Compile based on the selected MACHINE
if [[ ${MACHINE} == 'fx1000' ]] ; then
    # Build settings for the fx1000 machine
    cmake -B${BLD_DIR} -S. \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_RSM=OFF \
        -DCWBSUM=OFF  \
        -DTIMCOMCPL=OFF  \
        -DUSE_aeroclx=OFF

    	cmake --build ${BLD_DIR} -j $(($(nproc)/2))

elif [[ ${MACHINE} == 'a100' ]] ; then
    # Build settings for the a100 machine
    cmake -B${BLD_DIR} -S. \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_RSM=OFF \
        -DUSE_CUDA=ON \
        -DUSE_ACC=ON \
        -DUSE_PAR=OFF \
        -DUSE_SP=OFF  \
        -DCWBSUM=OFF  \
        -DTIMCOMCPL=OFF  \
        -DUSE_aeroclx=OFF
    cmake --build ${BLD_DIR} -j $(($(nproc)/2)) -v
else
    echo "[ERROR] Fatal error: unknown MACHINE!"
    exit 1
fi
