#!/bin/bash
set -e

# Initialize the Modules system
. $MODULESHOME/init/bash
#. $LMOD_ROOT/lmod/init/bash

# Set the machine type, default is "gpu"
MACHINE=${1:-"gpu"}


# Clear and reload the required modules
module purge

# Load the GFS modules
module use ../modulefiles
module load modulefile.tcogfs.${MACHINE}
module unuse modulefiles

# Set the build directory
BLD_DIR=build_${MACHINE}
[[ -e ${BLD_DIR} ]] && rm -rf ${BLD_DIR}


#Compile based on the selected MACHINE
if [[ ${MACHINE} == 'gpu' ]] ; then
    # Build settings for the a100 machine
    cmake -B${BLD_DIR} -S. \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_RSM=OFF \
        -DUSE_CUDA=ON \
        -DUSE_ACC=ON \
        -DUSE_PAR=OFF \
        -DUSE_SP=OFF  \
        -DCWBSUM=OFF  \
        -DTIMCOMCPL=ON  \
        -DUSE_aeroclx=OFF
    cmake --build ${BLD_DIR} -j $(($(nproc)/2)) -v
else
    echo "[ERROR] Fatal error: unknown MACHINE!"
    exit 1
fi
