#!/bin/ksh
set -x

echo 'in the configure'
# --------------- directory ------------------
export USERID=` whoami `
export DISK=` cd .. ; pwd `                    # top directory
export WORK=$DISK/run                          # working directory
export EXPN=` basename $WORK `                 # experimental subdirectory
export SDATE=${SDATE:-2023010100}
export TEMP=$DISK/wrk                          # RSM output directory
export BASEDIR=${TEMP}/DATA_GFS/gfs_${SDATE:2:8}_xnew # base field directory (data from GFS)
export FCSTHR=${FCSTHR:-1080}
export RESTRHR=${RESTRHR:-0}                   # restart hour (zero means NOT restart)
export FIXDIR=$DISK/fix
# --------------- compile options ----------------
# machine dependent
# compile options for ibm_xlf, mac_intel, mac_absoft, mac_xlf, linux_pgi, linux_gfortran, Fujitsu_fx10, Fujitsu_fx100
#export MACHINE=linux_intel
. ${WORK}/set_machine

# machine dependent cpp
export IBMSP=no
export FFT99M=yes
export DCRFT=no

export CWB_MPMD=no           # no: standalone RSM, yes: MPMD with CWBGFS
export CWB_CFS=no            # no: standalone RSM, yes: coupled with CWBCFS(+MOM6)
export CPL_TIMCOM=yes        # no: RSM without regional TIMCOM, yse: coupled with TIMCOM
export CWBSUM=yes           # yes: coupled with CWBCFS(+TIMCOM)
#
# massively parallel procesing options
export MARCH=mpi
export LAMMPI=no
export MPICH=yes
export MP=yes
export THREAD=no
export NCOL=16
export NROW=16
#
# model parameter
#
# compile model option
export NONHYD=no
export SIGP=yes              # sigma-p coordinate (yes/no)
#
export NDSL=yes              # NDSL, tracer part
export NDSLDYN=yes           # dynamic part of NDSL
#
export UPDIFF=yes
export NHDIFORD=2            # 4th-diffusion
export LEVTOP=2              # model top 2 layers 2nd diffusion.
#
export NDSLPPM=yes
export NDSLPPMV=yes
export Salpha=0.7

export STPLTB=yes            #set steep slope for lateral relaxation coefficients (pow-51). If STPLTB=no, pow-15 slope is used.
#
#-----physics parameterization-----
#
# run or not
#
export DCYC2=yes
export LSM=yes
export OZPHYS=yes
export GWDPS=yes
export do3DRT=yes
export CONCNV=yes
export SCONCNV=yes
export LRGSCL=yes
export wind_fitch=no
export LTN=no
export CHS=no
export spray=no
#
# schemes to choose
#
export NOAHLSM=yes           # noah land surface model
export LSMDATAREP=yes        # use reproduced landuse,soiltyp,vegfrac from high resolution source data
export SAMFSAS=yes           # scaleawareness SAS from NCEP physics, 2019.Sept.16
export YSU=yes
# microphysics 
export NMMIPH=12              # 2:Zhao-Carr; 3:Brad-Ferrier; 4:WSM3; 5:WSM5; 6:WSM6; 11:GFDLv1;12:GFDLv2;13:GFDLv3;15:GCE3Iv1
export NUMP3D=5              # 4:Zhao-Carr; 3:Brad-Ferrier; 3:WSM6 or GCE3Iv1; 5:GFDL; 
export NUMP2D=1              # 3:Zhao-Carr; 1:Brad-Ferrier; 1:WSM6 or GCE3Iv1; 1:GFDL; 
export NCLDB=5               # 1:Zhao-Carr; 1:Brad-Ferrier; 2:WSM3; 5:WSM6 or GFDL or GCE3Iv1
export NCLD=5                # 1:Zhao-Carr; 1:Brad-Ferrier; 2:WSM3; 5:WSM6 or GFDL or GCE3Iv1
#terr
export GMTED2010=yes         # Topography data source. When RUNRSMTERRAIN is yes, one of GMTED2010 and GTOPO30 must also be yes.
export GTOPO30=no            # Topography data source. When RUNRSMTERRAIN is yes, one of GMTED2010 and GTOPO30 must also be yes.

# compile exec option
export RMTN=no               # Legacy "rsm_rmtn" program
export RSMTERRAIN=yes        # New "rsm_terrain" program
export RLSMDATA=yes          # reproduce landuse,soiltyp,vegfrac from high resolution source data
export R3DRTDATA=yes         # adjust surface albedo by accounting for 3-D topography effect on surface solar radiation
export FCST=yes
#mpmd-unused#export RINP=yes

# --------------- run option --------------------
export LENMON=1
export DTIMES=3
export TIMESTEP=15           #5km, RSM
export TIMESTEP=`expr $TIMESTEP \* $DTIMES`
export IMDLPHY=1             # I/O of physics
export PRTHOUR=6             # output interval
export CLIM=1                # read climate data for initial field
export IRCLIM=0              # I(T)/O(F) of reading climate data per $READCLIMHR hour
export READCLIMHR=24         # read climate data interval (hour)

#mpmd-unused#export POSTTYPE=sync
export RUNRMTN=no            # Legacy "rsm_rmtn" program
export RUNRSMTERRAIN=yes     # New "rsm_terrain" program
export RUNLSMDATA=yes
export RUN3DRTDATA=yes
#mpmd-unused#export RUNRINP=yes
#mpmd-unused#export RUNRINP2=no
export RUNFCST=yes

# model parameter
export BGF=5                 # roughly equal to CDELX/RDELX

#### rsmlocation
export  IGRD=288
export  JGRD=288
export  LEVR=72
export  RPROJ=0.
export  RTRUTH=24.5
export  RORIENT=120.7
export  RDELX=5000.
export  RDELY=5000.
export  RCENLAT=24.5
export  RCENLON=120.7
export  RLFTGRD=144.
export  RBTMGRD=144.
#### rsmlocation1
# base field lat&lon (BCLAT1,BCLAT2,BCLON1,BCLON2) are defined by GFS namlist
export  BIGRD=215            # GFS nxs-1, need to run GFS first and check log to know nxs
export  BJGRD=151            # GFS mys-1, need to run GFS first and check log to know mys
export  BLEVR=72
export  BRDELX=25000.
export  BRDELY=25000.
#export  BRCENLAT=22.5
#export  BRCENLON=125.0
# from CWBGFS
export  BCPROJ=4.
export  BLEVS=72
export  BPGBRES=0.25         # 0.50 or 0.25
export  INCBASE=6            # 3 or 6 hours
export  BCIGRD1=$(echo "($BCLON2-($BCLON1))/$BPGBRES+1" | bc)
export  BCJGRD1=$(echo "($BCLAT2-($BCLAT1))/$BPGBRES+1" | bc)
#
#### for rsm post
export KO=16
#
# load default configure file
. $DISK/opt/rsm_default.option

# compile option
. $DISK/opt/compile.option.4cpl

